#!/usr/bin/env perl


# perlfetch v1.8.1 by danemasen contact@danemasen.com
# Project is under the ISC license


use Getopt::Long;

# Options under package namespace "opt::" with default values
{
 package opt;
 our $version;
 our $help;
 our $twelvehour;
 our $color = 1;
 our $date = 1;
 our $time = 1;
 our $host = 1;
 our $os = 1;
 our $flavor = 1;
 our $arch = 1;
 our $osversion = 1;
 our $terminal = 1;
 our $shell = 1;
 our $battery = 1;
}

# read and store environment variables
# disable the flags if the variables are set
$opt::color      = 0 if $ENV{NO_COLOR} ne "";
$opt::date       = 0 if $ENV{PERLFETCH_NO_DATE};
$opt::time       = 0 if $ENV{PERLFETCH_NO_TIME};
$opt::host       = 0 if $ENV{PERLFETCH_NO_HOST};
$opt::os         = 0 if $ENV{PERLFETCH_NO_OS};
$opt::flavor     = 0 if $ENV{PERLFETCH_NO_FLAVOR};
$opt::arch       = 0 if $ENV{PERLFETCH_NO_ARCH};
$opt::osversion  = 0 if $ENV{PERLFETCH_NO_VERSION};
$opt::terminal   = 0 if $ENV{PERLFETCH_NO_TERMINAL};
$opt::shell      = 0 if $ENV{PERLFETCH_NO_SHELL};
$opt::battery    = 0 if $ENV{PERLFETCH_NO_BATTERY};
$opt::twelvehour = $ENV{PERLFETCH_USE_12_HOUR};

# Parse options.
GetOptions (
 "help|h"     => \$opt::help,
 "version|v"  => \$opt::version,
 "twelvehour" => \$opt::twelvehour,

 # --no[option] for disabling --[option] to force enable
 # even if an environment variable was set
 "color!"     => \$opt::color,
 "date!"      => \$opt::date,
 "time!"      => \$opt::time,
 "host!"      => \$opt::host,
 "os!"        => \$opt::os,
 "flavor!"    => \$opt::flavor,
 "arch!"      => \$opt::arch,
 "osversion!" => \$opt::osversion,
 "terminal!"  => \$opt::terminal,
 "shell!"     => \$opt::shell,
 "battery!"   => \$opt::battery,
);

if (defined $opt::help) {
 print "Usage: perlfetch [-h -v] [--help --version]\n";
 print "\t-h, --help\t Show this help message.\n";
 print "\t-v, --version\t Show current version.\n";
 exit 0;
}

if (defined $opt::version) {
 print "1.8.1\n";
 exit 0;
}

# subroutine that fetches date
sub getDate {
 if (!$opt::color) {
  print(" DATE\t\t| ", `date +"%Y-%m-%d"`);
 } else {
  print(" \033[34;1mDATE\t\t|\033[0m ", `date +"%Y-%m-%d"`);
 }
}


# subroutine that fetches time
sub getTime {
 my $twelvehour_time = `date +"%I:%M "`;
 chomp $twelvehour_time;

 if (!$opt::color) {
  if ($opt::twelvehour == 1) {
   print(" TIME\t\t| ", $twelvehour_time);
   if (`date +"%H"` < 12) {
    print("am\n");
   } else {
    print("pm\n");
   }
  } else {
   print(" TIME\t\t| ", `date +"%H:%M"`);
  }
 } else {
  if ($opt::twelvehour == 1) {
   print(" \033[35;1mTIME\t\t|\033[0m ", $twelvehour_time);
   if (`date +"%H"` < 12) {
    print("am\n");
   } else {
    print("pm\n");
   }
  } else {
   print(" \033[35;1mTIME\t\t|\033[0m ", `date +"%H:%M"`);
  }
 }
}


# subroutine that fetches the host name of the current machine
sub getHostName {
 # if NO_COLOR environment variable is set to anything other than an empty string, print without color
 if (!$opt::color) {
  # print host name
  print(" HOST\t\t| ", `uname -n`);
 } else {
  # print host name
  print(" \033[37;1mHOST\t\t|\033[0m ", `uname -n`);
 }
}


# subroutine that fetches distribution of Linux
sub getFlavor {
 # store shell command in $flavor
 my $flavor = `lsb_release -sd`;
 # if $flavor contains "Linux" then remove quotes, otherwise ignore quotes
 if (index($flavor, "Linux") >= 0) {
  # parse stored command
  $flavor = substr $flavor, 1, -2;
  chomp $flavor;
  # if NO_COLOR environment variable is set to anything other than an empty string, print without color
  if (!$opt::color) {
   # print flavor of Linux without color
   print(" FLAVOR\t\t| ", $flavor, "\n");
  } else {
   # print flavor of Linux with color
   print(" \033[33;1mFLAVOR\t\t|\033[0m ", $flavor, "\n");
  }
 } else {
  # if NO_COLOR environment variable is set to anything other than an empty string, print without color
  if (!$opt::color) {
   # print flavor of Linux without color
   print(" FLAVOR\t\t| ", $flavor, "\n");
  } else {
   # print flavor of Linux with color
   print(" \033[33;1mFLAVOR\033[0m\t\t| ", $flavor, "\n");
  }
 }
}


# subroutine that fetches OS and prints Linux distro if OS is Linux
sub getOS {
 # store os name in $os variable
 my $os = `uname`;

 # if NO_COLOR environment variable is set to anything other than an empty string, print without color
 if (!$opt::color) {
  # print operating system without color
  print(" OS\t\t| ", $os);
 } else {
  # print operating system with color
  print(" \033[32;1mOS\t\t|\033[0m ", $os);
 }

 # if $os contains "Linux" then print $flavor otherwise ignore $flavor
 if (index($os, "Linux") != -1 && $opt::flavor == 1) {
  # print Linux distro
  getFlavor();
 } elsif (index($os, "Linux") != -1 && $opt::flavor == 1) {}
}


# subroutine that fetches the current architecture
sub getArch {
 # if NO_COLOR environment variable is set to anything other than an empty string, print without color
 if (!$opt::color) {
  # print machine's architecture without color
  print(" ARCHITECTURE\t| ", `uname -m`);
 } else {
  # print machine's architecture with color
  print(" \033[36;1mARCHITECTURE\t|\033[0m ", `uname -m`);
 }
}


# subroutine that fetches current OS or kernel version
sub getVersion {
 # if NO_COLOR environment variable is set to anything other than an empty string, print without color
 if (!$opt::color) {
  # print system version without color
  print(" VERSION\t| ", `uname -r`);
 } else {
  # print system version with color
  print(" \033[34;1mVERSION\t|\033[0m ", `uname -r`);
 }
}


# subroutine that fetches the current terminal being used
sub getTerminal {
 # if NO_COLOR environment variable is set to anything other than an empty string, print without color
 if (!$opt::color) {
  # print terminal used without color
  print(" TERMINAL\t| ", `echo \$TERM`);
 } else {
  # print terminal used with color
  print(" \033[32;1mTERMINAL\t|\033[0m ", `echo \$TERM`);
 }
}


sub getShell {
 # if NO_COLOR environment variable is set to anything other than an empty string, print without color
 if (!$opt::color) {
 # print shell used without color
 print(" SHELL\t\t| ", `echo \$SHELL`);
 } else {
 # print shell used with color
 print(" \033[35;1mSHELL\t\t|\033[0m ", `echo \$SHELL`);
 }
}


# subroutine that fetches battery capacity
sub getBattery {
 # store OS X shell command in $ioreg
 my $ioreg = system("ioreg --help 2>/dev/null");

 my $checkBSDBattery = `apm -l 2>/dev/null`;

 # if BAT0 and BAT1 exist, print their combined capacity divided by two
 if (-e "/sys/class/power_supply/BAT0/capacity" && -e "/sys/class/power_supply/BAT1/capacity") {
  # store contents of BAT0's capacity in $battery
  my $battery = `cat /sys/class/power_supply/BAT0/capacity` / 2;
  # store contents of BAT1's capacity in $battery1
  my $battery1 = `cat /sys/class/power_supply/BAT1/capacity` / 2;
  # remove \n character from $battery and $battery1
  chomp($battery, $battery1);

  # if NO_COLOR environment variable is set to anything other than an empty string, print without color
  if (!$opt::color) {
   # print current dual battery capacity without color
   print(" BATTERY\t| ", $battery + $battery1, "%\n");
  } else {
   # print current dual battery capacity with color
   print(" \033[36;1mBATTERY\t|\033[0m ", $battery + $battery1, "%\n");
  }
  # else if BAT0 exists
 } elsif (-e "/sys/class/power_supply/BAT0/capacity") {
  # store contents of BAT0 in $battery
  my $battery = `cat /sys/class/power_supply/BAT0/capacity`;
  # remove \n character
  chomp $battery;

  # if NO_COLOR environment variable is set to anything other than an empty string, print without color
  if (!$opt::color) {
   # print current single battery capacity without color
   print(" BATTERY\t| ", $battery, "%\n");
  } else {
   # print current single battery capacity with color
   print(" \033[36;1mBATTERY\t|\033[0m ", $battery, "%\n");
  }
  # else if ioreg command exists
 } elsif ($ioreg == 256) {
  # store OS X battery
  my $checkOSXBattery = `ioreg -l | grep -o '"CurrentCapacity" = \\d\\+' | grep -o '\\d*'`;
  # remove \n character
  chomp $checkOSXBattery;

  # if NO_COLOR environment variable is set to anything other than an empty string, print without color
  if (!$opt::color) {
   # print current OS X battery capacity without color
   print(" BATTERY\t| ", $checkOSXBattery, "%\n");
  } else {
   # print current OS X battery capacity
   print(" \033[36;1mBATTERY\t|\033[0m ", $checkOSXBattery, "%\n");
  }
 } elsif ($checkBSDBattery ne "") {
  chomp $checkBSDBattery;
  if (!$opt::color) {
   print(" BATTERY\t| ", $checkBSDBattery, "%\n");
  } else {
   print(" \033[36;1mBATTERY\t|\033[0m ", $checkBSDBattery, "%\n");
  }
 }
}


if ($opt::date == 1) {
 # print date
 getDate();
}

if ($opt::time == 1) {
 # print date
 getTime();
}

if ($opt::host == 1) {
 # print host name
 getHostName();
}

if ($opt::os == 1) {
 # print OS and Linux distro if os is Linux
 getOS();
}

if ($opt::arch == 1) {
 # print architecture
 getArch();
}

if ($opt::osversion == 1) {
 # print system version
 getVersion();
}

if ($opt::terminal == 1) {
 # print terminal used
 getTerminal();
}

if ($opt::shell == 1) {
 # print shell used
 getShell();
}

if ($opt::battery == 1) {
 # print battery capacity and status
 getBattery();
}

if ($opt::date != 1 && $opt::time != 1 && $opt::host != 1 && $opt::os != 1 && $opt::flavor != 1 && $opt::arch != 1 && $opt::osversion != 1 && $opt::terminal != 1 && $opt::shell != 1 && $opt::battery != 1) {
 if (!$opt::color) {
  print " All modules are disabled!\n";
 } else {
  print " \033[31;1mAll modules are disabled!\033[0m\n";
 }
}
