.TH PERLFETCH 1 perlfetch\-1.8.4
.SH NAME
.B Perlfetch - A Tiny System Information Script
.SH SYNOPSIS
.B perlfetch
.RB [ \-h\ \-v ]
.RB [ \-\-help\ \-\-version\ ...]
.SH DESCRIPTION
.P
Perlfetch is a simple system information fetching script that can be customized through environment variables and flags.
.SH USAGE
.SS Flags
.TP
.B \-h, \-\-help
Prints usage information and exits.
.TP
.B \-v, \-\-version
Prints the version number and exits.
.SH CUSTOMIZATION
.P
Customization can be done either with environment variables or flags. Flags take precedence over environment variables.
.SS Flags
.TP
.B \-\-nocolor, \-\-no\-color
Fully disables color output.
.TP
.B \-\-nodate, \-\-no\-date
Stops the date from being printed.
.TP
.B \-\-notime, \-\-no\-time
Stops the time from being printed.
.TP
.B \-\-twelvehour, \-\-twelve\-hour
Uses 12-hour time instead of 24-hour time.
.TP
.B \-\-nohost, \-\-no\-host
Stops the host name from being printed.
.TP
.B \-\-noos, \-\-no\-os
Stops the operating system from being printed. Also prevents the distribution of Linux from being printed, if applicable.
.TP
.B \-\-noflavor, \-\-no\-flavor
Stops the distribution of Linux from being printed. Only applicable on Linux systems.
.TP
.B \-\-noarch, \-\-no\-arch
Stops the system's architecture from being printed.
.TP
.B \-\-noversion, \-\-no\-version
Stops the kernel/system version from being printed.
.TP
.B \-\-noterminal, \-\-no\-terminal
Stops the current terminal in use, from being printed.
.TP
.B \-\-noshell, \-\-no\-shell
Stops the current shell in use, from being printed.
.TP
.B \-\-nobattery, \-\-no\-battery
Stops the current battery charge from being printed. Only applicable to Linux and OS X systems.
.SS Environment Variables
.TP
.B NO_COLOR
Fully disables color output. Follows the https://no-color.org standard, meaning if it's set to anything other than an empty string, no color will be printed.
.TP
.B PERLFETCH_NO_DATE
Stops the date from being printed. Valid values are 1-0.
.TP
.B PERLFETCH_NO_TIME
Stops the time from being printed. Valid values are 1-0.
.TP
.B PERLFETCH_USE_12_HOUR
Uses 12-hour time instead of 24-hour time. Valid values are 1-0.
.TP
.B PERLFETCH_NO_HOST
Stops the host name from being printed. Also prevents the distribution of Linux from being printed, if applicable. Valid values are 1-0.
.TP
.B PERLFETCH_NO_OS
Stops the operating system from being printed. Valid values are 1-0.
.TP
.B PERLFETCH_NO_FLAVOR
Stops the distribution of Linux from being printed. Only applicable on Linux systems. Valid values are 1-0.
.TP
.B PERLFETCH_NO_ARCH
Stops the system's architecture from being printed. Valid values are 1-0.
.TP
.B PERLFETCH_NO_VERSION
Stops the kernel/system version from being printed. Valid values are 1-0.
.TP
.B PERLFETCH_NO_TERMINAL
Stops the current terminal in use, from being printed. Valid values are 1-0.
.TP
.B PERLFETCH_NO_SHELL
Stops the current shell in use, from being printed. Valid values are 1-0.
.TP
.B PERLFETCH_NO_BATTERY
Stops the current battery charge from being printed. Only applicable to Linux and OS X systems. Valid values are 1-0.
.SH LICENSE
.P
ISC License
.P
Copyright (c) 2024 danemasen contact@danemasen.com
.P
Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.
.P
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
